services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_sf

  symfony:
    image: test_sf
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: test_sf
      DATABASE_USER: root
      DATABASE_PASSWORD: root
